name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-20.04, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Test module
      env:
        CIBW_BEFORE_BUILD: python scripts/fetch-vendor /tmp/vendor
        CIBW_BEFORE_BUILD_WINDOWS: python scripts\fetch-vendor C:\cibw\vendor
        CIBW_ENVIRONMENT: CFLAGS=-I/tmp/vendor/include LDFLAGS=-L/tmp/vendor/lib
        CIBW_ENVIRONMENT_WINDOWS: CL="/IC:\cibw\vendor\include" LINK="/LIBPATH:C:\cibw\vendor\lib"
        CIBW_SKIP: cp27-* cp35-* pp27-*
        CIBW_TEST_COMMAND: python setup.py test
      run: >-
        python -m pip install cibuildwheel;
        python -m cibuildwheel --output-dir wheelhouse
    # - name: Test module
    #   run: >-
    #     python setup.py test
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Build a source tarball
      run: >-
        python -m pip install --user --upgrade setuptools;
        python setup.py sdist;
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
